metaMonitoring:
  serviceMonitor:
    enabled: true

  dashboards:
    enabled: true

alertmanager:
  fallbackConfig: |
    global:
      resolve_timeout: 5m
      smtp_from: "Alertmanager <alertmanager@alertmanager.localhost>"
      smtp_smarthost: "mailpit.mailpit.svc.cluster.local:1025"
      smtp_require_tls: false
      # smtp_auth_username: ""
      # smtp_auth_password: ""

    route:
      receiver: "ixon"
      group_wait: 10s
      repeat_interval: 3h
      group_by: ["alertname", "priority", "container"]

    receivers:
      - name: "ixon"
        email_configs:
          - to: alerts@example.com
            send_resolved: true

nginx:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-ca-issuer
      traefik.ingress.kubernetes.io/router.middlewares: mimir-basicauth@kubernetescrd
    hosts:
      - host: mimir.monitoring
        paths:
          - path: /api/v1/push
            pathType: Prefix
    tls:
      - hosts:
          - mimir.monitoring
        secretName: mimir-tls

global:
  extraEnv:
    - name: JAEGER_ENDPOINT
      value: http://tempo-distributed-distributor.tempo.svc.cluster.local:14268/api/traces?format=jaeger.thrift

ingester:
  replicas: 3
  resources:
    limits:
      memory: 12Gi
    requests:
      cpu: 1
      memory: 2Gi

runtimeConfig:
  ingester_limits: # limits that each ingester replica enforces
    max_ingestion_rate: 0 #200000
    max_series: 0 #1500000
    max_tenants: 0 #1000
    max_inflight_push_requests: 0 #30000
  distributor_limits: # limits that each distributor replica enforces
    max_ingestion_rate: 0 #200000
    max_inflight_push_requests: 0 #30000
    max_inflight_push_requests_bytes: 0 #50000000
  overrides:
    anonymous: # limits for anonymous that the whole cluster enforces
      ingestion_tenant_shard_size: 0 #9
      max_global_series_per_user: 0 #1500000
      max_fetched_series_per_query: 0 #100000
      ruler_max_rules_per_rule_group: 0
      ruler_max_rule_groups_per_tenant: 0