apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: grafana-datasources
    files:
      - mimir.yaml
      - loki.yaml
      - alertmanager.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_datasource: "1"
