apiVersion: 1
datasources:
  - name: loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki-gateway.monitoring.svc.cluster.local
    isDefault: false
    editable: false
    jsonData:
      maxLines: "5000"
    version: 1
