replicas: 1

resources:
  # requests:
  #   cpu: 250m
  #   memory: 750Mi
  # limits:
  #   cpu: 500m
  #   memory: 1024Mi
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

serviceMonitor:
  enabled: true
  labels:
    scraper: prometheus-agent

testFramework:
  enabled: false

ingress:
  enabled: false
  path: /
  pathType: Prefix
  hosts:
    - grafana.tst.dtnfd.nl-016.lan.philips.com
  tls:
   - secretName: tst-wildcard
     hosts:
       - grafana.tst.dtnfd.nl-016.lan.philips.com
